# Generated by Django 2.2.dev20180602023146 on 2018-06-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0003_auto_20180604_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='jewellery',
        ),
        migrations.AddField(
            model_name='color',
            name='jewellery',
            field=models.ManyToManyField(to='jewellery.Jewellery'),
        ),
        migrations.AlterField(
            model_name='jewellery',
            name='id1',
            field=models.CharField(max_length=20),
        ),
    ]
